version: '3'
services:
  server:
    container_name: NODEJS_SERVER
    build: .
    volumes:
      - './:/node-app'
      - './node_modules:/node-app/node_modules'
    environment:
      NODE_ENV: development
      PORT: '${PORT}'
      PORT_PUBLISHED: '${PORT_PUBLISHED}'
      DB_URL: '${DB_URL}'
      SCRAPING_SERVICE: '${SCRAPING_SERVICE}'
      PROXY_URL: '${PROXY_URL}'
    depends_on:
      - db
    links:
      - db
    ports:
      - '${PORT_PUBLISHED}:${PORT}'
  db:
    image: mongo
    container_name: MONGODB_SERVER
    ports:
      - '5002:5002'
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
    name: mongo_nodejs
