version: '3'
services:
  server:
    container_name: NODEJS_SERVER
    build: .
    environment:
      NODE_ENV: development
      PORT: '${PORT}'
      PORT_PUBLISHED: '${PORT_PUBLISHED}'
      DB_URL: '${DB_URL}'
      SCRAPING_SERVICE_URL: '${SCRAPING_SERVICE_URL}'
      PROXY_URL: '${PROXY_URL}'
    depends_on:
      - db
    ports:
      - 5001:5001
    networks:
      - proxy-network
  db:
    image: mongo
    container_name: MONGODB_SERVER
    ports:
      - '5003:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  mongo:
    name: mongo_nodejs
